/**
 * HammerOn API: Easy control the band's songs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.4
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MusicOnlyIdAndMusicNameAndSingerNameDto } from './musicOnlyIdAndMusicNameAndSingerNameDto';
import { UserOnlyIdNameAndEmailDto } from './userOnlyIdNameAndEmailDto';

export interface EventWithMusicListDto {
    date: string;
    id?: string;
    musicList?: Array<MusicOnlyIdAndMusicNameAndSingerNameDto>;
    name: string;
    time?: string;
    userList?: Array<UserOnlyIdNameAndEmailDto>;
    utcDateTime: string;
    timeZoneName: string;
}
