import { UserOnlyIdNameAndEmailDto } from './userOnlyIdNameAndEmailDto';
import { MusicOnlyIdAndMusicNameAndSingerNameDto } from './musicOnlyIdAndMusicNameAndSingerNameDto';
/**
 * API for controlling church music
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MusicWithSingerAndLinksDto } from './musicWithSingerAndLinksDto';
import { UserDto } from './userDto';

export interface EventWithMusicListDto {
    date?: string;
    id?: string;
    musicList?: Array<MusicOnlyIdAndMusicNameAndSingerNameDto>;
    name?: string;
    time?: string;
    userList?: Array<UserOnlyIdNameAndEmailDto>;
}
