/**
 * API for controlling church music
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MusicLinkDto } from './musicLinkDto';
import { SingerDto } from './singerDto';

export interface MusicWithSingerAndLinksDto {
    id?: string;
    links?: Array<MusicLinkDto>;
    musicStatus: MusicWithSingerAndLinksDto.MusicStatusEnum;
    name: string;
    singer: SingerDto;
}
export namespace MusicWithSingerAndLinksDto {
    export type MusicStatusEnum = 'DISABLED' | 'ENABLED' | 'REJECTED';
    export const MusicStatusEnum = {
        ENABLED: 'ENABLED' as MusicStatusEnum,
        DISABLED: 'DISABLED' as MusicStatusEnum,
        REJECTED: 'REJECTED' as MusicStatusEnum
    };
}
