/**
 * API for controlling church music
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MusicLinkDto { 
    id?: string;
    link: string;
    typeLink: MusicLinkDto.TypeLinkEnum;
}
export namespace MusicLinkDto {
    export type TypeLinkEnum = 'CHORD' | 'SPOTIFY' | 'YOUTUBE';
    export const TypeLinkEnum = {
        CHORD: 'CHORD' as TypeLinkEnum,
        SPOTIFY: 'SPOTIFY' as TypeLinkEnum,
        YOUTUBE: 'YOUTUBE' as TypeLinkEnum
    };
}