/**
 * HammerOn API: Easy control the band's songs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.4
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventSimpleDto } from './eventSimpleDto';
import { MusicLinkDto } from './musicLinkDto';
import { SingerDto } from './singerDto';

export interface MusicDto { 
    events?: Array<EventSimpleDto>;
    id?: string;
    links?: Array<MusicLinkDto>;
    musicStatus?: MusicDto.MusicStatusEnum;
    name?: string;
    singer?: SingerDto;
}
export namespace MusicDto {
    export type MusicStatusEnum = 'DISABLED' | 'ENABLED' | 'REJECTED';
    export const MusicStatusEnum = {
        DISABLED: 'DISABLED' as MusicStatusEnum,
        ENABLED: 'ENABLED' as MusicStatusEnum,
        REJECTED: 'REJECTED' as MusicStatusEnum
    };
}