/**
 * HammerOn API: Easy control the band's songs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.4
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';

export interface SpaceDto { 
    approvedBy?: UserDto;
    approvedByDate?: Date;
    justification: string;
    name: string;
    requestedBy?: UserDto;
    requestedByDate?: Date;
    spaceId?: string;
}