/**
 * HammerOn API: Easy control the band's songs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.8
 * Contact: kb.developer.br@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SpaceApproveDto { 
    spaceStatusEnum: SpaceApproveDto.SpaceStatusEnumEnum;
}
export namespace SpaceApproveDto {
    export type SpaceStatusEnumEnum = 'APPROVED' | 'NEGATED' | 'REQUESTED';
    export const SpaceStatusEnumEnum = {
        APPROVED: 'APPROVED' as SpaceStatusEnumEnum,
        NEGATED: 'NEGATED' as SpaceStatusEnumEnum,
        REQUESTED: 'REQUESTED' as SpaceStatusEnumEnum
    };
}